### ISSUE TITLE
failed to install due to webxr-polyfill not having a package.json file

### ISSUE THREAD

**Issue by BryanChrisBrown** [kainino0x/holoplay-webxr#11]
currently the package.json file points to an empty webxr-polyfill folder as its source for `webxr-polyfill` 

given that this folder is empty and does not contain a package.json file, npm is unable to install it. 

In order to install the holoplay-webxr library currently the user has to manually override the path for the webxr-polyfill package.

**Comment by BryanChrisBrown** [comment]
after further looking into it it looks like this may be a git submodule issue

**Comment by kainino0x** [comment]
Oh yes, sounds like it. I should have mentioned that in my README!
