### ISSUE TITLE
Uncaught TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by michaelybecker** [kainino0x/holoplay-webxr#2]
![image](https://user-images.githubusercontent.com/10997806/118926701-a0d8e780-b8f5-11eb-9da9-711178857a47.png)

![image](https://user-images.githubusercontent.com/10997806/118926865-d251b300-b8f5-11eb-8709-6cfaa3d192ac.png)

Trying this in Chrome 90.0.4430.212 (Official Build) and looking glass portrait. Holoplay Studio is up and running. After some challenges, was able to run the unpacked extension and clone the right commit of the webxr samples, but I keep getting this error. Tried with and without the WebXR extension. Any idea what might be going on? Super keen to get webxr running on this beautiful device!

**Comment by kainino0x** [comment]
That sounds like something went wrong in the build... I don't know exactly what. This extension is standalone, it doesn't depend on another. However it probably conflicts with the WebXR Emulator extension.

The live demo pages work without any extensions installed: https://kai.graphics/holoplay-webxr/third_party/webxr-samples/
If that doesn't work, try disabling any of the WebXR extensions you do have installed.

**Comment by kainino0x** [comment]
Oh, I think this may happen if you try to build locally but you don't `git submodule update --init` first. This results in warnings (but unfortunately no errors) in the build.

**Comment by kainino0x** [comment]
Also note that there is a pre-built version in the repository, so you don't need to do this unless you're actually changing the code. You can just point Chrome/Firefox directly at your local, fresh clone of holoplay-webxr.
